Artifact v4

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -31,8 +31,16 @@ jobs:
         run: npm install
       - name: Build the project
         run: npm run build
-      - name: Upload artifact
-        uses: actions/upload-artifact@v1
+      
+      - name: Check for symlinks
+        run: |
+          if find ./out -type l | read; then
+            echo "Error: Symlinks found in the build output" >&2
+            exit 1
+          fi
+
+      - name: Upload build output
+        uses: actions/upload-artifact@v4
         with:
           name: github-pages
           path: ./out 
@@ -44,6 +52,12 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
+      - name: Download build artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: github-pages
+          path: ./out
+
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
